### ISSUE TITLE
Manuelle Installation / Manual installation

### ISSUE THREAD

**Issue by designpilot** [ErdmannFreunde/euf_conversion_tracking#1]
Ich musste die Erweiterung **euf_conversion_tracking** in **Contao 4.4.2** manuell installieren (im CM war diese zwar für die Installation ersichtlich "ohne Hinweis das diese nicht kompatibel sei" aber konnte nicht über den CM installiert werden, da in betreffender Datei der Versionshinweis fehlt).

**Manuelle Installation:**
- den entpackten ZIP Ordner "euf_conversion_tracking-develop" von GitHub umbenennen in "euf_conversion_tracking"
- den Ordner "euf_conversion_tracking" auf den Webserver in das Verzeichnis ./system/modules laden
- im CM auf Systemwartung -> Cache neu erstellen
- im CM auf Tools und auf den Link für das Installtool klicken
- im Installtool die DB aktualisieren

Soweit ist die Installation sauber durchgelaufen und im BE dann beim erstellen eines neuen FE Modules wird auch alles korrekt angezeigt (keine Fehlermeldungen).

------------------------------------------------------------------------------------------------

I had to install the extension **euf_conversion_tracking** in **Contao 4.4.2** manually (in the CM it was shown for the installation "without notice this is not compatible" but could not be installed via the CM because the corresponding file is missing the version hints).

**Manual installation:**
- Rename the unpacked ZIP folder "euf_conversion_tracking-develop" from GitHub to "euf_conversion_tracking"
- Load the folder "euf_conversion_tracking" on the web server in the directory ./system/modules
- In CM on System Maintenance -> Rebuild Cache
- In CM on Tools click on the link for the install tool
- In the install tool update the DB

As far as the installation went through cleanly and in the BE then when creating a new FE module everything is also displayed correctly (no error messages).

**Comment by denniserdmann** [comment]
Danke für den Test in Contao 4. Ich habe die Erweiterung für Version 4 freigegeben, sie lässt sich nun auch über den Contao Manager installieren.
